# Generated by Django 4.1 on 2022-08-12 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('agency', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumFrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('agency', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateField(null=True)),
                ('purchased_date', models.DateField(auto_now_add=True, null=True)),
                ('contains_ticket', models.BooleanField(null=True)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotocardFrime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200, null=True)),
                ('album_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.album')),
                ('albumfrime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.albumfrime')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.artist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photocard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200, null=True)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.artist')),
            ],
        ),
        migrations.AddField(
            model_name='albumfrime',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.artist'),
        ),
        migrations.AddField(
            model_name='albumfrime',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.artist'),
        ),
    ]
