# Generated by Django 4.1 on 2022-08-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_album_purchased_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumfrime',
            name='buyNumber',
        ),
    ]
