# Generated by Django 4.1 on 2022-08-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_albumfrime_buynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumfrime',
            name='buyNumber',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
