# Generated by Django 4.1 on 2022-08-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_albumfrime_buynumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='photocard',
            name='QR_image',
            field=models.ImageField(blank=True, null=True, upload_to='QR_image'),
        ),
    ]
