# Generated by Django 4.1 on 2022-08-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0007_remove_album_music_list_remove_albumfrime_music_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='gradient_color_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='gradient_color_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
