# Generated by Django 4.1 on 2022-08-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0008_artist_gradient_color_1_artist_gradient_color_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='play_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
