# Generated by Django 4.1 on 2022-08-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0009_music_play_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='logo_img'),
        ),
        migrations.RemoveField(
            model_name='album',
            name='music_list',
        ),
        migrations.AddField(
            model_name='album',
            name='music_list',
            field=models.ManyToManyField(blank=True, related_name='sang_music_list', to='album.music'),
        ),
    ]
