# Generated by Django 4.1 on 2022-08-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0010_artist_logo_image_remove_album_music_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='albumfrime',
            name='album_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
