# Generated by Django 4.0.4 on 2022-08-19 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0011_album_album_type_albumfrime_album_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='music_list',
        ),
        migrations.AddField(
            model_name='album',
            name='artist_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='albumfrime',
            name='artist_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='album',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='album.album'),
        ),
    ]
