# Generated by Django 4.1 on 2022-08-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userSubartist',
            field=models.ManyToManyField(default=True, to='album.album'),
        ),
    ]
