# Generated by Django 4.1 on 2022-08-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('user', '0002_user_usersubartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userBuyalbumList',
            field=models.ManyToManyField(default=True, related_name='buy_user', to='album.album'),
        ),
        migrations.AddField(
            model_name='user',
            name='usersSubaumList',
            field=models.ManyToManyField(default=True, related_name='sub_user2', to='album.album'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userSubartist',
            field=models.ManyToManyField(default=True, related_name='sub_user', to='album.album'),
        ),
    ]
