# Generated by Django 4.1 on 2022-08-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('user', '0003_user_userbuyalbumlist_user_userssubaumlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userBuyalbumList',
            new_name='userBuyalbum_type_List',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='usersSubaumList',
            new_name='usersSubalbum_type_List',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userSubartist',
        ),
        migrations.AddField(
            model_name='user',
            name='userSubartist_type_List',
            field=models.ManyToManyField(default=True, related_name='sub_user', to='album.artist'),
        ),
    ]
