# Generated by Django 4.1 on 2022-08-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_ticket_apply_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usersSubalbum_type_List',
            new_name='userSubalbum_type_List',
        ),
    ]
