# Generated by Django 4.1 on 2022-08-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_userssubalbum_type_list_user_usersubalbum_type_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userSubalbum_type_List',
            new_name='usersSubalbum_type_List',
        ),
    ]
